name: Remove Roboshop Infrastructure
on: [workflow_dispatch]
jobs:

  DEV-PLAN:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform Destroy
        run: terraform destroy -var-file=env-dev/main.tfvars


