name: provisioning roboshop Infra

on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: terraform init
        run: terraform init -backend-config=env-dev/state.tfvars

  QA:
    runs-on: ubuntu-latest
    needs: DEV
    steps:
      - run: echo Dummy job

  UAT:
    runs-on: ubuntu-latest
    needs: QA
    steps:
      - run: echo Dummy job

  PROD:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: terraform init
        run: terraform init -backend-config=env-prd/state.tfvars

